version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 10
    groups:
      microsoft:
        patterns:
          - "Microsoft.*"
        update-types:
          - "minor"
          - "patch"
      testing:
        patterns:
          - "*Test*"
          - "xunit*"
          - "Moq"
          - "FluentAssertions"
          - "coverlet*"
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    commit-message:
      prefix: "ci"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/FormFeeder.Api"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    commit-message:
      prefix: "docker"
      include: "scope"